jobs:
  - name: "Scan single ticker scanst"
    description: "Run scan of single ticker."
    container: "ghcr.io/marx2/scanst:latest"
    entrypoint: ["python", "main.py"]
    parameters:
      - "MSFT"
      - "--headless"
    env:
      SCRAB_USERNAME: "your_username"
      SCRAB_PASSWORD: "your_password"
      GRAPHQL_ENDPOINT: "http://graphql-mesh:80/graphql"
    resources:
      requests:
        cpu: "250m"
        memory: "64Mi"
      limits:
        cpu: "2000m"
        memory: "2Gi"
    namespace: "pfire"

  - name: "Test container"
    description: "Run an alpine echo."
    container: "alpine:latest"
    entrypoint: ["/bin/sh", "-c"]
    parameters: ["echo 'Job completed successfully!'"]
    namespace: "pfire"
