apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: networking
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
