---
logger:
  default: info
  logs:
    frigate.data_processing.real_time.face: debug
    frigate.embeddings: debug

auth:
  enabled: false

tls:
  enabled: false

mqtt:
  host: emqx.home.svc.cluster.local
  topic_prefix: frigate
  user: "${EMQX_MQTT_USER}"
  password: "${EMQX_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

detect:
  enabled: true
  fps: 5

ffmpeg:
  global_args: [-hide_banner, -loglevel, info]
  hwaccel_args: preset-vaapi

snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: 5

record:
  enabled: true
  motion:
    days: 5
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 10
      mode: motion
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 10
      mode: motion

face_recognition:
  enabled: true
  model_size: large
  detection_threshold: 0.3
  min_area: 100
  unknown_score: 0.7
  recognition_threshold: 0.5

objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 1000000
      threshold: 0.7

go2rtc:
  streams:
    cam-01:
      - rtsp://192.168.1.28/ch0_0.h264
    cam-01-sub:
      - rtsp://192.168.1.28/ch0_1.h264

cameras:
  cam-01:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam-01
          input_args: preset-rtsp-restream
          roles: [record]
        - path: rtsp://127.0.0.1:8554/cam-01-sub
          input_args: preset-rtsp-restream
          roles: [detect]
    detect:
      enabled: true
    objects:
      track:
        - person
        - bicycle
        - car
        - motorcycle
        - bus
        - boat
        - bird
        - cat
        - dog
        - horse
        - sheep
        - cow
        - bear
