---
apiVersion: v1
kind: Secret
metadata:
  name: scanst-secrets
  namespace: pfire
type: Opaque
stringData:
  POSTGREST_USER: "postgrest"
  POSTGREST_PASSWORD: "${POSTGREST_BASIC_AUTH}"
  SCRAB_USERNAME: "${SCRAB_LOGIN_NAME}"
  SCRAB_PASSWORD: "${SCRAB_PASSWORD}"
