apiVersion: v1
kind: ConfigMap
metadata:
  name: scanst-tickers
  namespace: pfire
data:
  TICKERS: "2382.TW AAPL ABNB ADBE ADP ADSK ADYEN.AS AFYA ALGN AMD AMZN ANET APTV ARM ASML ASRNL.AS AVGO AZO BABA BMRN CDNS CMG COST CP.TO CPRT CRH CRM CRWD CSCO CSGP CSU.TO CTAS CYBR DECK DHR DT DV DXCM EFX EL EPAM ETSY EVO.ST EXLS FDS FI FICO FIVE FTNT FVRR GD GFS GOOGL GQG.AX HQY HUBS HWM HXL IAS IDXX INTC INTU IRDM ISRG JHX KNEBV.HE LLY LMAT LULU MA MBLY MELI META MNST MPWR MRVL MSCI MSFT MTD NBIX NE NEE NFLX NOW 7974.T NU NVDA ODFL OKTA OLED PANW PATK PAYC PCTY PDD PINS PLTR POOL PTC QLYS QRVO RGEN RVTY SAIA SAP.DE SHOP.TO SKX SNOW SNPS SQ SRT.DE TER TIH.TO TMO TOI.V TREX TRU TSLA TSM TTD TXN UBER VEEV WDAY WKL.AS YETI ZS ZTS ADI LRCX SFM UNH NVO NET VRT GRAB DSGX CELH"
