---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanst
  namespace: pfire
spec:
  #   The cron expression to run a job twice a day, once at 6 PM and once at 10 PM
  schedule: "0 1 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        created-by: scanst
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          containers:
            - name: scanst
              image: ghcr.io/marx2/scanst:1.0.7
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: scanst-tickers
              env:
                - name: TZ
                  value: "${TZ}"
                - name: SCRAB_USERNAME
                  value: "${SCRAB_LOGIN_NAME}"
                - name: SCRAB_PASSWORD
                  value: "${SCRAB_PASSWORD}"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: GRAPHQL_ENDPOINT
                  value: "http://graphql-mesh:80/graphql"
                - name: DELAY_BETWEEN_METRICS
                  value: "5"

