---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scanst
  namespace: pfire
spec:
  #   The cron expression to run a job twice a day, once at 6 PM and once at 10 PM
  schedule: "0 1 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        created-by: scanst
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: regcred
          restartPolicy: Never
          containers:
            - name: scanst
              image: ghcr.io/marx2/scanst:v1.0.13
              imagePullPolicy: IfNotPresent
              args: ["--headless"]
              envFrom:
                - secretRef:
                    name: scanst-secrets
              env:
                - name: TZ
                  value: "${TZ}"
                - name: LOG_LEVEL
                  value: "INFO"
                - name: GRAPHQL_ENDPOINT
                  value: "http://graphql-mesh:80/graphql"
                - name: DELAY_BETWEEN_METRICS
                  value: "1.5"
