# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/containers/resources/limits]
        target:
          kind: Pod
  values:
    global:
      createDefaultServiceAccount: false
    serviceAccount:
      weave-gitops: {}
    defaultPodOptions:
      automountServiceAccountToken: true
    controllers:
      weave-gitops:
        serviceAccount:
          identifier: weave-gitops
        initContainers:
          gen-certs:
            image:
              repository: docker.io/library/alpine
              tag: 3.24
            command:
              - sh
              - -c
              - |
                apk add --no-cache openssl &&
                openssl req -x509 -newkey rsa:2048 -keyout /tls/tls.key -out /tls/tls.crt -days 3650 -nodes -subj '/CN=weave-gitops'
        containers:
          app:
            image:
              repository: ghcr.io/weaveworks/wego-app
              tag: v0.39.0-rc.2
            env:
              WEAVE_GITOPS_FEATURE_OIDC_BUTTON_LABEL: ""
              WEAVE_GITOPS_FEATURE_TELEMETRY: "false"
              WEAVE_GITOPS_FEATURE_OIDC: "false"
            args:
              - --tls-cert-file=/tls/tls.crt
              - --tls-private-key-file=/tls/tls.key
              - --auth-methods=user-account
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true

    persistence:
      tls:
        type: emptyDir
        globalMounts:
          - path: /tls

    service:
      app:
        controller: weave-gitops
        ports:
          http:
            port: 9001

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Weave GitOps"
          hajimari.io/icon: "mdi:sync"
          hajimari.io/group: "networking"
          hajimari.io/info: "Flux UI"
        hosts:
          - host: &host "weave-gitops.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
