apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-cpp-models
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
