---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capacitor-next
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      createDefaultServiceAccount: false
    serviceAccount:
      capacitor-next: {}
    defaultPodOptions:
      automountServiceAccountToken: true
    controllers:
      app:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          identifier: capacitor-next
        containers:
          app:
            env:
              TZ: ${TZ}
            envFrom:
              - configMapRef:
                  name: capacitor-next
                  optional: true
            image:
              repository: ghcr.io/gimlet-io/capacitor-next
              tag: 0.14.0@sha256:95368be3e6b473108a3ccdfc15c22ed1a99475e4b92d6b11c983887dbee1860a
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
            probes:
              startup:
                enabled: false
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                    scheme: HTTP
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
    service:
      app:
        controller: app
        ports:
          http:
            port: 8080
    ingress:
      app:
        enabled: true
        className: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Capacitor Next"
          hajimari.io/icon: mdi:sync
          hajimari.io/group: networking
          hajimari.io/info: Flux UI (next)
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
        hosts:
          - host: &host "capacitor-next.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
