---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: convertx
  namespace: default
spec:
  hosts:
    - convertx.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: convertx
    kind: Deployment
    apiVersion: apps/v1
    service: convertx
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
