---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: openst
  namespace: pfire
spec:
  hosts:
    - openst.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: openst
    kind: Deployment
    apiVersion: apps/v1
    service: openst
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
