apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: bitmappery
  namespace: media
spec:
  hosts:
    - bitmappery.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: bitmappery
    kind: Deployment
    apiVersion: apps/v1
    service: app
    port: 5173
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
