apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hass-k8s
  labels:
    app.kubernetes.io/name: hass-k8s
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["patch"]
  - apiGroups: ["apps"]
    resources:
      - deployments/scale
      - statefulsets/scale
      - statefulsets/status
    verbs: ["get", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "cronjobs/status", "jobs"]
    verbs: ["get", "list", "watch", "patch", "update", "create", "delete"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments/scale"]
    verbs: ["get", "patch", "update"]
