---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastra-ticker-data
  namespace: pfire
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: longhorn
