---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: jobshot
  namespace: pfire
spec:
  hosts:
    - jobshot.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: jobshot
    kind: Deployment
    apiVersion: apps/v1
    service: jobshot
    port: 3000
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
