apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: pictshare
  namespace: networking
spec:
  hosts:
    - pictshare.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: pictshare
    kind: Deployment
    apiVersion: apps/v1
    service: app
    port: 80
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
