apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: networking
data:
  configuration.yaml: |
    log:
      level: info
    theme: dark
    authentication_backend:
      file:
        path: /secrets/users_database.yaml
    session:
      name: authelia_session
      cookies:
        - domain: ${SECRET_DOMAIN}
          authelia_url: https://authelia.${SECRET_DOMAIN}
      redis:
        host: authelia-redis.networking.svc.cluster.local
        port: 6379
    storage:
      local:
        path: /config/db.sqlite3
    notifier:
      filesystem:
        filename: /config/notification.txt
    access_control:
      default_policy: one_factor
