apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: networking
data:
  configuration.yaml: |
    log:
      level: info
    theme: dark
    authentication_backend:
      ldap:
        address: ldap://lldap.networking.svc.cluster.local:3890
        base_dn: ${LLDAP_BASE_DN}
        username_attribute: uid
        additional_users_dn: ou=people
        users_filter: (&({username_attribute}={input})(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (member={dn})
        group_name_attribute: cn
        mail_attribute: mail
        display_name_attribute: displayName
        user: uid=admin,ou=people,${LLDAP_BASE_DN}
        password: ${LLDAP_LDAP_USER_PASS}
    session:
      name: authelia_session
      cookies:
        - domain: ${SECRET_DOMAIN}
          authelia_url: https://authelia.${SECRET_DOMAIN}
      redis:
        host: authelia-redis.networking.svc.cluster.local
        port: 6379
    storage:
      local:
        path: /config/db.sqlite3
    notifier:
      filesystem:
        filename: /config/notification.txt
    access_control:
      default_policy: one_factor
