# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/containers/resources/limits]
        target:
          kind: Pod
  values:
    controllers:
      authelia-redis:
        containers:
          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.10.1
            command: [redis-server, --save, "60", "1", --loglevel, warning]
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: [ALL]
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 256Mi
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
    service:
      redis:
        controller: authelia-redis
        ports:
          redis:
            port: 6379
