apiVersion: v1
kind: Secret
metadata:
  name: authelia-users
  namespace: networking
stringData:
  users_database.yaml: |
    users:
      ${AUTHELIA_ADMIN_USER}:
        displayname: "Admin"
        password: "${AUTHELIA_ADMIN_PASSWORD_HASH}"
        email: "${AUTHELIA_ADMIN_EMAIL}"
        groups:
          - admins
