---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefox2-config-pvc
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
