# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: firefox2
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
      - paths: [/spec/containers/resources/limits]
        target:
          kind: Pod
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      firefox2:
        replicas: 0
        containers:
          app:
            image:
              repository: docker.io/browserless/chrome
              tag: latest
            args:
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --enable-features=SharedClipboard,UseOzonePlatform
              - --ozone-platform=wayland
            env:
              TZ: ${TZ}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      app:
        controller: firefox2
        ports:
          http:
            port: 3000

    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/icon: "firefox"
          hajimari.io/info: Internet browser with clipboard
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: keda-http-interceptor-proxy
                  port: 8080
        tls:
          - hosts:
              - *host

    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config
