---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: pgweb
  namespace: pfire
spec:
  hosts:
    - pgweb.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: pgweb
    kind: Deployment
    apiVersion: apps/v1
    service: pgweb
    port: 8081
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
