---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kusionstack
  namespace: flux-system
spec:
  interval: 24h
  url: https://kusionstack.github.io/charts