---
apiVersion: v1
kind: Secret
metadata:
  name: apprise-secret
  namespace: monitoring
stringData:
  apprise.yml: |
    version: 1
    urls:
      - ntfy://${NTFY_ADMIN_USER}:${NTFY_ADMIN_PASSWORD}@ntfy.monitoring.svc.cluster.local/alerts
