apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: chromium
  namespace: home
spec:
  hosts:
    - chromium.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: chromium
    kind: Deployment
    apiVersion: apps/v1
    service: chromium
    port: 6901
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
