---
apiVersion: v1
kind: Secret
metadata:
  name: sheets-sync-secrets
  namespace: pfire
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${PORTFOLIOST_GOOGLE_CLIENT_SECRET}"
  GOOGLE_REFRESH_TOKEN: "${PORTFOLIOST_GOOGLE_REFRESH_TOKEN}"
