apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: sshwifty
  namespace: home
spec:
  hosts:
    - sshwifty.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: sshwifty
    kind: Deployment
    apiVersion: apps/v1
    service: sshwifty
    port: 8182
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
