apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authelia-oidc-operator
  namespace: flux-system
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.0.1-28369932470-SNAPSHOT
  url: oci://ghcr.io/brunnels/charts/authelia-oidc-operator
