use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG"
  privacypolicy_url: false
  contact_url: false
  enable_metrics: false

server:
  secret_key: "change_me"  # overridden by SEARXNG_SECRET env var
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false
  public_instance: false
  image_proxy: false
  forwarded_allow_ips: "*"

ui:
  static_use_hash: true
  default_locale: ""
  infinite_scroll: false
  default_theme: simple
  theme_args:
    simple_style: auto

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "auto"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html
    - json

outgoing:
  request_timeout: 3.0
  max_request_timeout: 10.0
  pool_connections: 100
  pool_maxsize: 10

engines:
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
  - name: wikidata
    disabled: true
