apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pocket-id-operator
  namespace: networking
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: pocket-id-operator
    namespace: networking
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/containers/resources/limits]
        target:
          kind: Pod
  values:
    operator:
      replicas: 1
      timezone: ${TZ}

    pocket-id-instance:
      instance:
        enabled: true
        spec:
          image: ghcr.io/pocket-id/pocket-id:v2.13.0-distroless@sha256:ccb590169770feb5b23ba16d49386514a2c26a77e95bb687b442ae09f17c15da
          encryptionKey:
            valueFrom:
              secretKeyRef:
                name: pocket-id-secret
                key: ENCRYPTION_KEY
          env:
            - name: TZ
              value: ${TZ}
            - name: APP_URL
              value: https://pocket-id.${SECRET_DOMAIN}
            - name: DB_PROVIDER
              value: sqlite
            - name: LDAP_ENABLED
              value: "true"
            - name: LDAP_HOST
              value: lldap.networking.svc.cluster.local
            - name: LDAP_PORT
              value: "3890"
            - name: LDAP_BASE_DN
              value: ${LLDAP_BASE_DN}
            - name: LDAP_BIND_DN
              value: uid=admin,ou=people,${LLDAP_BASE_DN}
            - name: LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lldap-secret
                  key: LLDAP_LDAP_USER_PASS
          persistence:
            enabled: true
            existingClaim: pocket-id-data
