apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oci-repository.yaml
  - pvc.yaml
  - secret.yaml
  - ingress.yaml
  - ldap-sync-cronjob.yaml
  - helmrelease.yaml
  - portfoliost-oidc-client.yaml
