apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data
  namespace: networking
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
