---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: cachest
  namespace: pfire
spec:
  hosts:
    - cachest.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: cachest
    kind: Deployment
    apiVersion: apps/v1
    service: cachest
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
