---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cachest-redis
  namespace: pfire
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
