---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pfire-stooq-rw-pv
  labels:
    app: nfs-pfire-stooq-rw-pv
spec:
  storageClassName: pfire-stooq-rw
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.49
    path: /volume1/kubernetes/pfire/data
  mountOptions:
    - nfsvers=4.1
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pfire-stooq-rw-pvc
  namespace: pfire
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: pfire-stooq-rw
  resources:
    requests:
      storage: 100Gi
