---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: capacitor
rules:
  - apiGroups:
      - ""
      - apps
      - batch
      - autoscaling
      - networking.k8s.io
      - policy
      - rbac.authorization.k8s.io
      - events.k8s.io
    resources:
      - pods
      - pods/log
      - services
      - endpoints
      - configmaps
      - secrets
      - events
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
      - serviceaccounts
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
      - ingresses
      - networkpolicies
      - jobs
      - cronjobs
      - horizontalpodautoscalers
      - poddisruptionbudgets
      - roles
      - clusterroles
      - rolebindings
      - clusterrolebindings
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - source.toolkit.fluxcd.io
      - kustomize.toolkit.fluxcd.io
      - helm.toolkit.fluxcd.io
      - infra.contrib.fluxcd.io
    resources:
      - gitrepositories
      - ocirepositories
      - buckets
      - helmrepositories
      - helmcharts
      - kustomizations
      - helmreleases
      - terraforms
    verbs:
      - get
      - watch
      - list
      - patch
  - apiGroups:
      - keda.sh
    resources:
      - scaledjobs
      - scaledobjects
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capacitor
subjects:
  - kind: ServiceAccount
    name: capacitor
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: capacitor
  apiGroup: rbac.authorization.k8s.io
