---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ntfy-data-pvc.yaml
  - ntfy-secret.yaml
  - helmrelease.yaml
