---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-reframe-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-reframe
  resources:
    requests:
      storage: 1Mi
