---
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: searxng
  namespace: default
spec:
  hosts:
    - searxng.${SECRET_DOMAIN}
  pathPrefixes:
    - /
  scaleTargetRef:
    name: searxng
    kind: Deployment
    apiVersion: apps/v1
    service: searxng
    port: 8080
  replicas:
    min: 0
    max: 1
  scaledownPeriod: 300
