---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - regcred.yaml
  - crunchy-postgres-secret.yaml
  - postgrescluster-pfire.yaml
  #  - hasura
  #  - grafana
  - pgadmin/ks.yaml
  - graphql-mesh
  - stooq-importer/ks.yaml
  - redis/ks.yaml
  #  - ghostfolio/ks.yaml
  - stooq
  - postgrest/ks.yaml
  - captchasolver
  - swaggerui/ks.yaml
  - pgdb/ks.yaml
  - scanst/ks.yaml
  - scorest/ks.yaml
  #  - grist
  - investbrain/ks.yaml
  - jobshot/ks.yaml
  - pgweb/ks.yaml
  - cachest/ks.yaml
  - openst/ks.yaml
  - stooq-downloader/ks.yaml
