---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reframe
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3

  values:
    global:
      createDefaultServiceAccount: false

    controllers:
      reframe:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/stefexec/reframe
              tag: v1.3.1

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:movie-edit"
          hajimari.io/group: "media"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      uploads:
        existingClaim: nfs-media-reframe-pvc
        globalMounts:
          - path: /app/uploads
            subPath: uploads
      exports:
        existingClaim: nfs-media-reframe-pvc
        globalMounts:
          - path: /app/exports
            subPath: exports
      fonts:
        existingClaim: nfs-media-reframe-pvc
        globalMounts:
          - path: /app/fonts
            subPath: fonts
      models:
        existingClaim: nfs-media-reframe-pvc
        globalMounts:
          - path: /app/models
            subPath: models
