---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drawio
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: [/spec/replicas]
        target:
          kind: Deployment
      - paths: [/spec/containers/resources/limits]
        target:
          kind: Pod
  values:
    global:
      createDefaultServiceAccount: false
    controllers:
      drawio:
        replicas: 0
        containers:
          drawio:
            image:
              repository: jgraph/drawio
              tag: 30.3.12@sha256:0783b3a1e793dfd71a02076f71a21050682ea4fa404630c5666c582ffae5e6b6
            env:
              TZ: ${TZ}
              DRAWIO_SELF_CONTAINED: "1"
              DRAWIO_SERVER_URL: https://drawio.${SECRET_DOMAIN}/
              DRAWIO_BASE_URL: https://drawio.${SECRET_DOMAIN}
              DRAWIO_VIEWER_URL: https://drawio.${SECRET_DOMAIN}/js/viewer.min.js
              EXPORT_URL: http://localhost:8000/
            securityContext:
              runAsUser: 1001
              runAsGroup: 999
              fsGroup: 999
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 128Mi
          export: # shit ain't working yet...
            image:
              repository: jgraph/export-server
              tag: latest@sha256:b064faf6ceb27cfff3674d18d72d48e4fc22bee6588c2467b5b8baeaf505ca60
            env:
              DRAWIO_BASE_URL: https://draw.${SECRET_DOMAIN}
            securityContext:
              runAsUser: 999
              runAsGroup: 999
              fsGroup: 999
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            resources:
              limits:
                cpu: 200m
                memory: 512Mi
              requests:
                cpu: 50m
                memory: 128Mi

    service:
      drawio:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      external:
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: "https://auth.${SECRET_DOMAIN}/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}/oauth2/start
          hajimari.io/enable: "true"
          hajimari.io/appName: "draw.io"
          hajimari.io/icon: simple-icons:diagramsdotnet
          hajimari.io/group: "media"
          hajimari.io/info: Diagramming and flowchart tool
        hosts:
          - host: &host drawio.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: keda-http-interceptor-proxy
                  port: 8080
        tls:
          - hosts: [*host]
